---

- name: Download synapse workers doc
  local_action:
    module: get_url
    url: https://github.com/matrix-org/synapse/raw/master/docs/workers.md
    dest: "{{ role_path }}/files/workers.upstream-documentation.md"
  vars:
     ansible_become: no

- name: Download synapse workers doc and convert into YAML
  local_action:
    module: shell
    cmd: "awk -f '{{ role_path }}/files/workers-doc-to-yaml.awk' -- '{{ role_path }}/files/workers.upstream-documentation.md' > '{{ role_path }}/vars/workers.yml'"
    creates: "{{ role_path }}/vars/workers.yml"
  vars:
     ansible_become: no

- name: Load list of available worker apps and endpoints
  include_vars: "{{ role_path }}/vars/workers.yml"

- name: Ensure synapse worker base service file installed
  template:
    src: "{{ role_path }}/templates/synapse/systemd/matrix-synapse-worker@.service.j2"
    dest: "{{ matrix_systemd_path }}/matrix-synapse-worker@.service"
    mode: 0644
  register: matrix_synapse_worker_systemd_service_result

- name: Ensure previous worker service symlinks are cleaned
  file:
    path: "{{ item.root + '/' + item.path }}"
    state: absent
  when:
    - item.state == 'link'
    - item.path is match('matrix-synapse-worker@.*\\.service')
  with_filetree:
    - "{{ matrix_systemd_path }}/matrix-synapse.service.wants"

- name: Ensure systemd reloaded the worker service unit
  service:
    daemon_reload: yes

- name: Ensure individual worker service symlinks exist
  service:
    name: "matrix-synapse-worker@{{ item.type }}:{{ item.port }}.service"
    enabled: true
  with_items: "{{ matrix_synapse_workers_enabled_list }}"

- name: Ensure previous worker configs are cleaned
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ matrix_synapse_config_dir_path }}/worker.*.yaml"

- name: Ensure creation of specific worker configs
  template:
    src: "{{ role_path }}/templates/synapse/worker.yaml.j2"
    dest: "{{ matrix_synapse_config_dir_path }}/worker.{{ item.type }}:{{ item.port }}.yaml"
  with_list: "{{ matrix_synapse_workers_enabled_list }}"

- name: Add workers to synapse.wants list
  set_fact:
    matrix_synapse_systemd_wanted_services_list: >
      {{ matrix_synapse_systemd_wanted_services_list +
      ['matrix-synapse-worker@' + item.type + ':' + item.port|string + '.service'] }}
  with_items: "{{ matrix_synapse_workers_enabled_list }}"

- name: Ensure matrix-synapse-worker-write-pid script is created
  copy:
    src: "{{ role_path }}/files/usr-local-bin/matrix-synapse-worker-write-pid"
    dest: "{{ matrix_local_bin_path }}/matrix-synapse-worker-write-pid"
    mode: 0750

- name: Ensure jq is installed (Archlinux)
  pacman:
    name:
      - jq
    state: present
  when: (ansible_distribution == 'Archlinux')

- name: Ensure jq is installed (CentOS)
  yum:
    name:
      - jq
    state: present
  when: (ansible_distribution == 'CentOS')

- name: Ensure jq is installed (Debian)
  apt:
    name:
      - jq
    state: present
  when: (ansible_os_family == 'Debian')
